# Generated by Django 3.0.7 on 2020-07-12 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_buy',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 53, 39, 97190)),
        ),
        migrations.AlterField(
            model_name='ordersuccess',
            name='date_done',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 53, 39, 99188)),
        ),
        migrations.AlterField(
            model_name='paydone',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 53, 39, 98188)),
        ),
    ]
