# Generated by Django 3.0.7 on 2020-07-12 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200712_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_buy',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 10, 194263)),
        ),
        migrations.AlterField(
            model_name='ordersuccess',
            name='date_done',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 10, 196261)),
        ),
        migrations.AlterField(
            model_name='paydone',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 10, 195262)),
        ),
    ]
