# Generated by Django 3.0.7 on 2020-07-12 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200712_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_buy',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 27, 132879)),
        ),
        migrations.AlterField(
            model_name='ordersuccess',
            name='date_done',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 27, 133878)),
        ),
        migrations.AlterField(
            model_name='paydone',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 27, 132879)),
        ),
    ]
