# Generated by Django 3.0.7 on 2020-07-12 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200712_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_buy',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 1, 4, 17, 48489)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='notice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordersuccess',
            name='date_done',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 1, 4, 17, 50488)),
        ),
        migrations.AlterField(
            model_name='paydone',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 1, 4, 17, 49488)),
        ),
        migrations.AlterField(
            model_name='paydone',
            name='notice',
            field=models.TextField(blank=True, default=''),
        ),
    ]
