# Generated by Django 3.0.7 on 2020-06-23 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200623_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_buy',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 0, 5, 13, 394163)),
        ),
    ]
